#ifndef PRUNE_H
# define PRUNE_H

# include <stdbool.h>
# include <stdint.h>
# include "movetable.h"

/// A pruning table answers "how many moves do I need AT LEAST to reach the
/// goal from here?" with one array lookup. The search uses it to drop a
/// branch as soon as "moves used so far + this number" is already over
/// budget (docs/en/02-algorithms.md).
///
/// One table covers TWO coordinates at once (a "pair", e.g. twist and
/// slice), because a pair knows more than either one alone. The pair
/// (a, b) is stored at index a * count_b + b, one byte each: the fewest
/// moves that take (a, b) to (0, 0), the value the solved cube gives for
/// every coordinate.
///
/// How it is built (prune_build): breadth-first search from the goal.
/// Depth 0 is just (0, 0). Everything one move from a depth-d pair is
/// depth d + 1, unless it was already reached sooner. Turning a cube
/// works the same forwards and backwards (every move has an undo in the
/// set), so "moves from the goal to here" equals "moves from here to the
/// goal". Because each pair gets its EXACT distance in the pair's space,
/// the value can never overestimate the real distance: the real cube has
/// to solve both coordinates at once, so it needs at least that many moves.
/// That is what "admissible" means (docs/en/GLOSSARY.md).

/// Sentinel: a pair that the search has not reached (yet). Real distances
/// are far below 255, so it can never be a real answer. After a finished
/// build no cell holds it, because every pair can be reached.
# define PRUNE_UNVISITED 0xFF

/// One pruning table for a pair of coordinates.
///
/// - dist:    count_a * count_b bytes, indexed by prune_index().
/// - count_b: how many values the second coordinate has (the row width).
/// - size:    count_a * count_b, the number of cells.
/// - depth:   the biggest distance in the table (how many BFS layers).
typedef struct s_prune_table
{
	uint8_t	*dist;
	int		count_b;
	int		size;
	int		depth;
}	t_prune_table;

/// The four tables the two-phase solver needs.
///
/// - twist_slice, flip_slice: phase 1, moves = all 18.
/// - cperm_sperm, eperm_sperm: phase 2, moves = the 10 of MOVES_PHASE2.
typedef struct s_prune_tables
{
	t_prune_table	twist_slice;
	t_prune_table	flip_slice;
	t_prune_table	cperm_sperm;
	t_prune_table	eperm_sperm;
}	t_prune_tables;

/// @brief Cell number of the pair (a, b) in a table.
static inline int	prune_index(const t_prune_table *table, int a, int b)
{
	return (a * table->count_b + b);
}

/// @brief Fewest moves from the pair (a, b) to the goal (a lower bound for
///        the real cube).
static inline int	prune_dist(const t_prune_table *table, int a, int b)
{
	return (table->dist[prune_index(table, a, b)]);
}

/// @brief Builds one pruning table by breadth-first search from (0, 0).
///
/// Uses only the moves in `moves`, looked up in the two move tables (an
/// illegal MT_ILLEGAL cell is never read as long as `moves` is a subset of
/// what that table supports).
///
/// @param table   Filled in (allocated). Its old contents are ignored.
/// @param move_a  Move table of the first coordinate.
/// @param count_a How many values the first coordinate has.
/// @param move_b  Move table of the second coordinate.
/// @param count_b How many values the second coordinate has.
/// @param moves   Moves the search may use.
/// @return true on success. On false (malloc failed) nothing is allocated.
bool	prune_build(t_prune_table *table, const uint16_t *move_a, int count_a,
			const uint16_t *move_b, int count_b, t_move_mask moves);

/// @brief Frees one table and zeroes it. Safe to call twice.
void	prune_free(t_prune_table *table);

/// @brief Forward breadth-first search from state 0, using only `moves`.
///
/// Marks every value of one coordinate that is reachable from 0 — used to
/// find the members of a subgroup (e.g. Thistlethwaite's G3,
/// docs/en/10-thistlethwaite-spec.md §3): a subgroup generated by `moves`
/// is exactly the set of values reachable from 0 using only `moves`.
///
/// @param table Move table of one coordinate (e.g. cperm).
/// @param count How many values that coordinate has.
/// @param moves Moves allowed during the walk.
/// @return A malloc'd bool[count], true where reachable. NULL on OOM; the
///         caller frees it with free().
bool	*reachable_set(const uint16_t *table, int count, t_move_mask moves);

/// @brief Builds a pruning table whose goal is a SET of pairs, not just
///        (0, 0): every pair (a, b) with goal_a[a] && goal_b[b] starts at
///        distance 0 instead. Everything else about the search is
///        identical to prune_build(), and for the same reason (every move
///        has its own undo within `moves`) the result is still each
///        pair's EXACT distance to its nearest goal member, so it still
///        never overestimates.
///
/// @param goal_a Membership array from reachable_set(), size count_a.
/// @param goal_b Membership array from reachable_set(), size count_b.
/// @return true on success. On false (malloc failed) nothing is allocated.
bool	prune_build_coset(t_prune_table *table, const uint16_t *move_a,
			int count_a, const bool *goal_a, const uint16_t *move_b,
			int count_b, const bool *goal_b, t_move_mask moves);

/// @brief Builds all four tables from the move tables.
/// @return true on success. On false nothing is left allocated.
bool	prune_tables_build(t_prune_tables *tables, const t_move_tables *moves);

/// @brief Frees all four tables. Safe to call twice.
void	prune_tables_free(t_prune_tables *tables);

/// @brief Lower bound on the moves phase 1 still needs (to twist 0, flip 0,
///        slice 0): the bigger of its two tables. Taking the biggest is
///        valid; adding them would not be (one move helps both tables).
static inline int	prune_phase1(const t_prune_tables *tables, int twist,
	int flip, int slice)
{
	int	a;
	int	b;

	a = prune_dist(&tables->twist_slice, twist, slice);
	b = prune_dist(&tables->flip_slice, flip, slice);
	if (a > b)
		return (a);
	return (b);
}

/// @brief Lower bound on the moves phase 2 still needs (to a solved cube),
///        with the 10 phase-2 moves. Only meaningful once phase 1 is done.
static inline int	prune_phase2(const t_prune_tables *tables, int cperm,
	int eperm, int sperm)
{
	int	a;
	int	b;

	a = prune_dist(&tables->cperm_sperm, cperm, sperm);
	b = prune_dist(&tables->eperm_sperm, eperm, sperm);
	if (a > b)
		return (a);
	return (b);
}

#endif
